// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package message

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage(in *jlexer.Lexer, out *SendMessageResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MessageID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage(out *jwriter.Writer, in SendMessageResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.MessageID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SendMessageResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SendMessageResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SendMessageResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SendMessageResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage(l, v)
}
func easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage1(in *jlexer.Lexer, out *SendMessageRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatId = int64(in.Int64())
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage1(out *jwriter.Writer, in SendMessageRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatId))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SendMessageRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SendMessageRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SendMessageRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SendMessageRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage1(l, v)
}
func easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage2(in *jlexer.Lexer, out *GetMessagesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "messages":
			if in.IsNull() {
				in.Skip()
				out.Messages = nil
			} else {
				in.Delim('[')
				if out.Messages == nil {
					if !in.IsDelim(']') {
						out.Messages = make([]GetMessagesRecord, 0, 0)
					} else {
						out.Messages = []GetMessagesRecord{}
					}
				} else {
					out.Messages = (out.Messages)[:0]
				}
				for !in.IsDelim(']') {
					var v1 GetMessagesRecord
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Messages = append(out.Messages, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "next_cursor":
			if in.IsNull() {
				in.Skip()
				out.NextCursor = nil
			} else {
				if out.NextCursor == nil {
					out.NextCursor = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.NextCursor = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage2(out *jwriter.Writer, in GetMessagesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"messages\":"
		out.RawString(prefix[1:])
		if in.Messages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Messages {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"next_cursor\":"
		out.RawString(prefix)
		if in.NextCursor == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.NextCursor))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetMessagesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetMessagesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetMessagesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetMessagesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage2(l, v)
}
func easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage3(in *jlexer.Lexer, out *GetMessagesRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "chat_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChatId = int64(in.Int64())
			}
		case "cursor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cursor = string(in.String())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage3(out *jwriter.Writer, in GetMessagesRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ChatId))
	}
	{
		const prefix string = ",\"cursor\":"
		out.RawString(prefix)
		out.String(string(in.Cursor))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetMessagesRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetMessagesRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetMessagesRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetMessagesRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage3(l, v)
}
func easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage4(in *jlexer.Lexer, out *GetMessagesRecord) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.MessageID).UnmarshalText(data))
				}
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = int64(in.Int64())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage4(out *jwriter.Writer, in GetMessagesRecord) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.MessageID).MarshalText())
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.Int64(int64(in.From))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetMessagesRecord) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetMessagesRecord) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson56de76c1EncodeGithubComThxhixChatInternalTransportHttpMessage4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetMessagesRecord) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetMessagesRecord) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson56de76c1DecodeGithubComThxhixChatInternalTransportHttpMessage4(l, v)
}
